version: '3'

services:
  trino:
    image: trinodb/trino
    container_name: oltrino
    networks:
      - trino-ol
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/event-listener.properties:/etc/trino/event-listener.properties
      - ${PWD}/target/trino-openlineage-442:/usr/lib/trino/plugin/openlineage
  olapi:
    image: mockserver/mockserver
    container_name: olapi
    environment:
      MOCKSERVER_SERVER_PORT: 5000
    networks:
      - trino-ol
    ports:
      - 5000:5000

networks:
  trino-ol:
